### ISSUE TITLE
Exception when trying to cycle hero

### ISSUE THREAD

**Issue by saltyoverflow** [doombubbles/in-game-hero-switch#2]
Can't cycle heros. Every time i press the cycle shortcut the following message spawns in melon loader:

```
System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Unity.UI_New.InGame.StoreMenu.TowerPurchaseButton Il2CppAssets.Scripts.Unity.UI_New.InGame.RightMenu.ShopMenu.GetTowerButtonFromBaseId(System.String)'.
   at InGameHeroSwitch.InGameHeroSwitchMod.ChangeHero(Int32 delta)
   at InGameHeroSwitch.InGameHeroSwitchMod.OnUpdate() in /home/runner/work/in-game-hero-switch/in-game-hero-switch/InGameHeroSwitch/InGameHeroSwitchMod.cs:line 89
   at MelonLoader.MelonEventBase`1.Invoke(Action`1 delegateInvoker) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 143
```

I don't even have a `D:\a\` Folder on my computer, no idea why the mod is expecting something there.
Reinstalling TD6, Modloader and the mod did not help.

**Comment by KendyPls** [comment]
Same issue here, error below:

```
[17:20:25.663] [In-Game_Hero_Switch] System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Unity.UI_New.InGame.StoreMenu.TowerPurchaseButton Il2CppAssets.Scripts.Unity.UI_New.InGame.RightMenu.ShopMenu.GetTowerButtonFromBaseId(System.String)'.
   at InGameHeroSwitch.InGameHeroSwitchMod.ChangeHero(Int32 delta)
   at InGameHeroSwitch.InGameHeroSwitchMod.OnUpdate() in /home/runner/work/in-game-hero-switch/in-game-hero-switch/InGameHeroSwitch/InGameHeroSwitchMod.cs:line 89
   at MelonLoader.MelonEventBase`1.Invoke(Action`1 delegateInvoker) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 143
[17:20:27.190] [In-Game_Hero_Switch] System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Unity.UI_New.InGame.StoreMenu.TowerPurchaseButton Il2CppAssets.Scripts.Unity.UI_New.InGame.RightMenu.ShopMenu.GetTowerButtonFromBaseId(System.String)'.
   at InGameHeroSwitch.InGameHeroSwitchMod.ChangeHero(Int32 delta)
   at InGameHeroSwitch.InGameHeroSwitchMod.OnUpdate() in /home/runner/work/in-game-hero-switch/in-game-hero-switch/InGameHeroSwitch/InGameHeroSwitchMod.cs:line 93
   at MelonLoader.MelonEventBase`1.Invoke(Action`1 delegateInvoker) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 143
```

**Comment by Senseweeks** [comment]
I am having the same issue. Its a shame i would really like to use this mod.

**Comment by doombubbles** [comment]
Sorry I forgot to fix this version of the mod, I've mainly been keeping this feature up to date as part of https://github.com/doombubbles/useful-utilities#readme

**Comment by Senseweeks** [comment]
I see that it is included but it does not have the ability to cycle when the hero is placed (in order to get multiple heroes) as this mod did

**Comment by doombubbles** [comment]
Ok pushed a new version https://github.com/doombubbles/in-game-hero-switch/releases/tag/1.1.4

**Comment by Senseweeks** [comment]
using the 1.1.4

[23:08:56.293] [In-Game_Hero_Switch] System.NullReferenceException: Object reference not set to an instance of an object.
   at InGameHeroSwitch.InGameHeroSwitchMod.ChangeHero(Int32 delta) in /home/runner/work/in-game-hero-switch/in-game-hero-switch/InGameHeroSwitch/InGameHeroSwitchMod.cs:line 37
   at InGameHeroSwitch.InGameHeroSwitchMod.OnUpdate() in /home/runner/work/in-game-hero-switch/in-game-hero-switch/InGameHeroSwitch/InGameHeroSwitchMod.cs:line 89
   at MelonLoader.MelonEventBase`1.Invoke(Action`1 delegateInvoker) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 143

**Comment by Senseweeks** [comment]
The latest patch (1.1.5) seems to have resolved this issue for me!
